<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.yandex.practicum</groupId>
    <artifactId>blog-project</artifactId>
    <name>Practicum blog project</name>
    <modules>
        <module>blog-backend</module>
        <module>blog-frontend</module>
    </modules>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <failOnMissingWebXml>false</failOnMissingWebXml>

        <vaadin.version>24.6.6</vaadin.version>
        <drivers.downloader.phase>pre-integration-test</drivers.downloader.phase>
        <jetty.version>12.0.15</jetty.version>

        <spring.data.version>2024.1.1</spring.data.version>
        <spring.webmvc.version>6.2.1</spring.webmvc.version>
        <jakarta.servlet.version>4.0.2</jakarta.servlet.version>
        <thymeleaf.version>3.1.2.RELEASE</thymeleaf.version>
        <jakarta.validation.version>3.0.2</jakarta.validation.version>
        <lombok.version>1.18.36</lombok.version>
        <jackson.annotations.version>2.15.3</jackson.annotations.version>
        <mapstruct.version>1.5.2.Final</mapstruct.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <spring.data.jdbc.version>3.4.1</spring.data.jdbc.version>
        <javax.persistence.version>2.2</javax.persistence.version>
        <hibernate.version>5.6.9.Final</hibernate.version>
        <spring.orm.version>5.3.18</spring.orm.version>
        <h2database.version>2.2.224</h2database.version>
        <spring.test.version>6.2.1</spring.test.version>
        <junit.version>5.11.2</junit.version>
        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
        <maven.war.plugin.version>3.4.0</maven.war.plugin.version>
    </properties>

    <repositories>
        <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <!-- Repository used by many Vaadin add-ons -->
        <repository>
            <id>Vaadin Directory</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>apache snapshots</id>
            <url>https://repository.apache.org/content/repositories/snapshots</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->
        <pluginRepository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-bom</artifactId>
                <version>${spring.data.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <type>pom</type>
                <scope>import</scope>
                <version>${vaadin.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
</project>
