hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true

jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://db:5432/blog
jdbc.username=postgres
jdbc.password=postgres