CREATE TABLE IF NOT EXISTS "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "image" bytea,
  "text" varchar,
  "likes" int
);

CREATE TABLE IF NOT EXISTS "tags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint,
  "name" varchar(255)
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint,
  "comment" varchar
);

ALTER TABLE "tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
