CREATE TABLE IF NOT EXISTS "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) not null,
  "image" bytea,
  "text" varchar not null,
  "likes" int not null
);

CREATE TABLE IF NOT EXISTS "tags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint not null,
  "tag_name" varchar(255) not null
);

CREATE TABLE  IF NOT EXISTS "posts_tags" (
   "post_id" bigint,
   "tag_id" bigint
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint not null,
  "comment" varchar not null
);

ALTER TABLE "posts_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE;;

ALTER TABLE "posts_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE;;

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE;;