spring:
  profiles:
    active: prod

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/blog
  username: postgres
  password: postgres

vaadin:
  servlet:
    url-mapping: /main-view/*